import { ReactNode, ButtonHTMLAttributes } from "react";
import { ChipSkeleton } from "./components";

export interface ChipComponents {
  Skeleton: typeof ChipSkeleton;
}

export interface ChipProperties {
  /** 
   Text to be displayed on chip.
  */
  text: string;
  /**
   * SVG icon to be displayed on chip.
   * @TJS-type React.ReactNode
   */
  icon?: ReactNode;
  /**
   * Informs whether the close icon should be displayed.
   */
  removable?: boolean;
  /**
   * Highlights the chip to indicate its value was generated by AI.
   * Applies AI gradient border and an AI focus ring.
   */
  aiGenerated?: boolean;
}

export type ChipProps = ChipProperties &
  ButtonHTMLAttributes<HTMLButtonElement | HTMLDivElement>;
