import { TextareaHTMLAttributes } from "react";
import { TextareaSkeleton } from "./components";

export interface TextareaComponents {
  Skeleton: typeof TextareaSkeleton;
}

export interface TextareaProperties {
  /**
   * Change the visual style of the textarea.
   * @default neutral
   */
  appearance?:
    | "neutral"
    | "success"
    | "warning"
    | "danger"
    | "ai-generative"
    | "transparent";
  /**
   * Highlights the field to indicate its value was generated by AI.
   * Applies AI gradient border, white background and an AI focus ring.
   */
  aiGenerated?: boolean;
  /**
   * Number of lines to be rendered for the user to input text
   * @default 2
   */
  lines?: number;
  /**
   * Controls intrinsic sizing behavior of the field. When true, the textarea will grow with content up to the maxLines limit (if provided) and then scroll.
   * @default false
   */
  autoGrow?: boolean;
  /**
   * Caps the textarea visual height to the given number of lines.
   * When used together with autoGrow=true, the textarea will grow
   * with content up to this limit and then scroll.
   */
  maxLines?: number;
  /**
   * Sets the minimum height of the textarea to the given number of lines.
   * The textarea will never shrink below this height, even when empty.
   */
  minLines?: number;
  /**
   * ID of the textarea
   * */
  id: string;
  /**
   * Enable/disable textarea resize functionality
   * @default true
   */
  resize?: boolean;
}

export type TextareaBaseProps = TextareaProperties &
  TextareaHTMLAttributes<HTMLTextAreaElement>;
