nodeLinker: node-modules

changesetIgnorePatterns:
  - "**/*.spec.{ts,tsx}"
  - "**/*.stories.{ts,tsx}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
