import { createThemeContract } from "@vanilla-extract/css";

export const vars = createThemeContract({
  colors: {
    primary: {
      surface: "primary-surface",
      surfaceHighlight: "primary-surfaceHighlight",
      interactive: "primary-interactive",
      interactiveHover: "primary-interactiveHover",
      interactivePressed: "primary-interactivePressed",
      textLow: "primary-textLow",
      textHigh: "primary-textHigh",
    },
    success: {
      surface: "success-surface",
      surfaceHighlight: "success-surfaceHighlight",
      interactive: "success-interactive",
      interactiveHover: "success-interactiveHover",
      interactivePressed: "success-interactivePressed",
      textLow: "success-textLow",
      textHigh: "success-textHigh",
    },
    warning: {
      surface: "warning-surface",
      surfaceHighlight: "warning-surfaceHighlight",
      interactive: "warning-interactive",
      interactiveHover: "warning-interactiveHover",
      interactivePressed: "warning-interactivePressed",
      textLow: "warning-textLow",
      textHigh: "warning-textHigh",
    },
    danger: {
      surface: "danger-surface",
      surfaceHighlight: "danger-surfaceHighlight",
      interactive: "danger-interactive",
      interactiveHover: "danger-interactiveHover",
      interactivePressed: "danger-interactivePressed",
      textLow: "danger-textLow",
      textHigh: "danger-textHigh",
    },
    neutral: {
      background: "neutral-background",
      surface: "neutral-surface",
      surfaceDisabled: "neutral-surfaceDisabled",
      surfaceHighlight: "neutral-surfaceHighlight",
      interactive: "neutral-interactive",
      interactiveHover: "neutral-interactiveHover",
      interactivePressed: "neutral-interactivePressed",
      textDisabled: "neutral-textDisabled",
      textLow: "neutral-textLow",
      textHigh: "neutral-textHigh",
    },
  },
  fontFamily: {
    centranube: "fontFamily.centranube",
  },
  fontSize: {
    body: {
      caption: "fontSize.body.caption",
      base: "fontSize.body.base",
      highlight: "fontSize.body.highlight",
    },
    title: {
      h1: "fontSize.title.h1",
      h2: "fontSize.title.h2",
      h3: "fontSize.title.h3",
      h4: "fontSize.title.h4",
      h5: "fontSize.title.h5",
      h6: "fontSize.title.h6",
    },
  },
  fontWeight: {
    regular: "fontWeight.regular",
    medium: "fontWeight.medium",
    bold: "fontWeight.bold",
  },
  lineWeight: {
    body: {
      caption: "lineWeight.caption.small",
      base: "lineWeight.base.small",
      highlight: "lineWeight.body.highlight",
    },
    title: {
      h1: "lineWeight.title.h1",
      h2: "lineWeight.title.h2",
      h3: "lineWeight.title.h3",
      h4: "lineWeight.title.h4",
      h5: "lineWeight.title.h5",
      h6: "lineWeight.title.h6",
    },
  },
  shadow: {
    level: {
      0: "shadow.light.level.0",
      1: "shadow.light.level.1",
      2: "shadow.light.level.2",
      3: "shadow.light.level.3",
      4: "shadow.light.level.4",
      5: "shadow.light.level.5",
    },
  },
  shape: {
    border: {
      radius: {
        "0,5": "sizes.0,5",
        "1": "sizes.1",
        "2": "sizes.2",
        "3": "sizes.3",
        "4": "sizes.4",
        "5": "sizes.5",
        "6": "sizes.6",
        full: "9999px",
        base: "sizes.1,5",
        half: "50%",
      },
      width: {
        "1": "0.0625rem",
        "2": "sizes.0,5",
        "3": "0.1875rem",
        "4": "sizes.1",
        "5": "0.3125rem",
      },
    },
  },
  spacing: {
    "0,5": "spacing.0,5",
    "1": "spacing.1",
    "2": "spacing.2",
    "4": "spacing.4",
    "6": "spacing.6",
    "8": "spacing.8",
    "10": "spacing.10",
    "12": "spacing.12",
    "14": "spacing.14",
    "16": "spacing.16",
    "18": "spacing.18",
    "20": "spacing.20",
  },
  sizes: {
    "0,5": "sizes.0,5",
    "1": "sizes.1",
    "1,5": "sizes.1,5",
    "2": "sizes.2",
    "2,5": "sizes.2,5",
    "3": "sizes.3",
    "3,5": "sizes.3,5",
    "4": "sizes.4",
    "4,5": "sizes.4,5",
    "5": "sizes.5",
    "6": "sizes.6",
    "7": "sizes.7",
    "8": "sizes.8",
    "9": "sizes.9",
    "10": "sizes.10",
    "11": "sizes.11",
    "12": "sizes.12",
    "14": "sizes.14",
    "16": "sizes.16",
    "18": "sizes.18",
    "20": "sizes.20",
  },
  motion: {
    speed: {
      base: "motion.speed.base",
      fast: "motion.speed.fast",
      slow: "motion.speed.slow",
      slower: "motion.speed.slower",
    },
  },
  breakpoint: {
    xs: "breakpoint.xs",
    md: "breakpoint.md",
    lg: "breakpoint.lg",
    xl: "breakpoint.xl",
  },
  utils: {
    focus: "0 0 0 3px primary.surfaceHighlight",
  },
});
