import { createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract(
  {
    colors: {
      primary: {
        surface: "",
        surfaceHighlight: "",
        interactive: "",
        interactiveHover: "",
        interactivePressed: "",
        textLow: "",
        textHigh: "",
      },
      success: {
        surface: "",
        surfaceHighlight: "",
        interactive: "",
        interactiveHover: "",
        interactivePressed: "",
        textLow: "",
        textHigh: "",
      },
      warning: {
        surface: "",
        surfaceHighlight: "",
        interactive: "",
        interactiveHover: "",
        interactivePressed: "",
        textLow: "",
        textHigh: "",
      },
      danger: {
        surface: "",
        surfaceHighlight: "",
        interactive: "",
        interactiveHover: "",
        interactivePressed: "",
        textLow: "",
        textHigh: "",
      },
      neutral: {
        background: "",
        surface: "",
        surfaceDisabled: "",
        surfaceHighlight: "",
        interactive: "",
        interactiveHover: "",
        interactivePressed: "",
        textDisabled: "",
        textLow: "",
        textHigh: "",
      },
    },
    fontFamily: {
      sans: "",
      mono: "",
    },
    fontSize: {
      body: {
        caption: "",
        base: "",
        highlight: "",
      },
      title: {
        h1: "",
        h2: "",
        h3: "",
        h4: "",
        h5: "",
        h6: "",
      },
    },
    fontWeight: {
      regular: "",
      medium: "",
      bold: "",
    },
    lineWeight: {
      body: {
        caption: "",
        base: "",
        highlight: "",
      },
      title: {
        h1: "",
        h2: "",
        h3: "",
        h4: "",
        h5: "",
        h6: "",
      },
    },
    shadow: {
      level: {
        0: "",
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
      },
    },
    shape: {
      border: {
        radius: {
          "0-5": "",
          1: "",
          2: "",
          3: "",
          4: "",
          5: "",
          6: "",
          full: "",
          base: "",
          half: "",
        },
        width: {
          1: "",
          2: "",
          3: "",
          4: "",
          5: "",
        },
      },
    },
    spacing: {
      "0-5": "",
      1: "",
      "1-5": "",
      2: "",
      "2-5": "",
      3: "",
      "3-5": "",
      4: "",
      "4-5": "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
      12: "",
      14: "",
      16: "",
      18: "",
      20: "",
    },
    zIndex: {
      100: "",
      200: "",
      300: "",
      400: "",
      500: "",
      600: "",
      700: "",
      800: "",
      900: "",
    },
    motion: {
      speed: {
        base: "",
        fast: "",
        slow: "",
        slower: "",
      },
    },
    breakpoint: {
      xs: "",
      md: "",
      lg: "",
      xl: "",
    },
    utils: {
      focus: "",
    },
  },
  (_value, path) => `nimbus-${path.join("-")}`
);
