import fs from "fs";
import path from "path";

/**
 * Renders the body of the "Storybook preview is ready" pull request comment,
 * deep-linking every component the pull request touches.
 *
 * Story ids are read from the `index.json` emitted by `storybook build` instead
 * of being guessed from the `title` of a `*.stories.tsx` file: Storybook's own
 * sanitizer collapses dots, slashes and repeated separators (`Atomic/Input/
 * Input.Password` becomes `atomic-input-input-password`), so any hand-rolled
 * slug eventually produces a dead link.
 *
 * Usage (reads the changed file list from a file, or from stdin):
 *   STORYBOOK_URL=https://host/index.html yarn preview:links changed-files.txt
 */

const DEFAULT_INDEX_PATH = ".build-storybook/index.json";
const MAX_LINKS = 8;

/** Every published component lives in its own directory under these two roots. */
const COMPONENT_ROOT_PATTERN =
  /^packages\/react\/src\/(?:atomic|composite)\/[^/]+/;

/** Style definitions live in their own package, keyed by the component name. */
const STYLES_COMPONENT_PATTERN =
  /^packages\/core\/styles\/src\/packages\/(?:atomic|composite)\/([^/]+)/;

/** Generated by `yarn build:docs`, never a reason to point at a component. */
const IGNORED_FILE_PATTERN = /\.docs\.json$/;

/** Lets the workflow find its own comment again without matching on prose. */
export const COMMENT_MARKER = "<!-- nimbus-storybook-preview -->";

export interface StorybookIndexEntry {
  id: string;
  title: string;
  importPath: string;
  type: string;
}

export interface StorybookIndex {
  entries: Record<string, StorybookIndexEntry>;
}

export interface StoryTarget {
  title: string;
  docsId: string | null;
  storyId: string | null;
}

const DOCS_ENTRY_TYPE = "docs";
const STORY_ENTRY_TYPE = "story";

const normalizePath = (importPath: string): string =>
  importPath.replace(/^\.\//, "");

const directoryOf = (filePath: string): string => path.posix.dirname(filePath);

const isSelfOrDescendant = (ancestor: string, directory: string): boolean =>
  directory === ancestor || directory.startsWith(`${ancestor}/`);

const byDepthThenName = (a: string, b: string): number =>
  a.split("/").length - b.split("/").length || a.localeCompare(b);

/**
 * Groups the flat Storybook index by the stories file each entry came from,
 * keeping the docs page and the first story of every file.
 */
const groupByStoriesFile = (
  index: StorybookIndex
): Map<string, StoryTarget> => {
  const targets = new Map<string, StoryTarget>();

  for (const entry of Object.values(index.entries ?? {})) {
    const storiesFile = normalizePath(entry.importPath);
    const target = targets.get(storiesFile) ?? {
      title: entry.title,
      docsId: null,
      storyId: null,
    };

    if (entry.type === DOCS_ENTRY_TYPE && !target.docsId) {
      target.docsId = entry.id;
    }
    if (entry.type === STORY_ENTRY_TYPE && !target.storyId) {
      target.storyId = entry.id;
    }

    targets.set(storiesFile, target);
  }

  return targets;
};

/** `fileUploader`, `FileUploader` and `file-uploader` all name one component. */
const normalizeComponentName = (name: string): string =>
  name.toLowerCase().replace(/-/g, "");

/**
 * Maps a change in `@nimbus-ds/styles` back to the component it styles. Those
 * files live outside the component tree, so they are matched by name.
 */
const resolveStyledComponentRoot = (
  changedFile: string,
  storiesFiles: string[]
): string | null => {
  const styledComponent = STYLES_COMPONENT_PATTERN.exec(changedFile)?.[1];
  if (!styledComponent) return null;

  const wanted = normalizeComponentName(styledComponent);

  return (
    storiesFiles
      .map((storiesFile) => COMPONENT_ROOT_PATTERN.exec(storiesFile)?.[0])
      .find(
        (componentRoot): componentRoot is string =>
          Boolean(componentRoot) &&
          normalizeComponentName(path.posix.basename(String(componentRoot))) ===
            wanted
      ) ?? null
  );
};

/**
 * Finds the stories file that best describes a changed file: the one sitting in
 * the closest ancestor directory, so a change to `InputPassword` links to the
 * `Input.Password` page rather than to `Input`.
 */
const resolveStoriesFile = (
  changedFile: string,
  storiesFiles: string[]
): string | null => {
  if (storiesFiles.includes(changedFile)) return changedFile;

  const componentRoot =
    COMPONENT_ROOT_PATTERN.exec(changedFile)?.[0] ??
    resolveStyledComponentRoot(changedFile, storiesFiles);
  if (!componentRoot) return null;

  const candidates = storiesFiles.filter((storiesFile) =>
    isSelfOrDescendant(componentRoot, directoryOf(storiesFile))
  );
  if (candidates.length === 0) return null;

  const changedDirectory = directoryOf(changedFile);
  const [nearest] = candidates
    .filter((storiesFile) =>
      isSelfOrDescendant(directoryOf(storiesFile), changedDirectory)
    )
    .sort((a, b) => directoryOf(b).length - directoryOf(a).length);

  if (nearest) return nearest;

  // Files that sit outside every stories directory — the package manifest, the
  // changelog — still belong to the component, so fall back to its entry point.
  return [...candidates].sort(byDepthThenName)[0];
};

export const resolveStoryTargets = (
  changedFiles: string[],
  index: StorybookIndex
): StoryTarget[] => {
  const targetsByStoriesFile = groupByStoriesFile(index);
  const storiesFiles = [...targetsByStoriesFile.keys()];
  const resolved = new Map<string, StoryTarget>();

  for (const changedFile of changedFiles) {
    if (IGNORED_FILE_PATTERN.test(changedFile)) continue;

    const storiesFile = resolveStoriesFile(changedFile, storiesFiles);
    if (!storiesFile) continue;

    const target = targetsByStoriesFile.get(storiesFile);
    if (target) resolved.set(storiesFile, target);
  }

  return [...resolved.values()].sort((a, b) => a.title.localeCompare(b.title));
};

export const previewUrl = (baseUrl: string, target: StoryTarget): string => {
  const storyPath = target.docsId
    ? `/docs/${target.docsId}`
    : `/story/${target.storyId}`;
  const separator = baseUrl.includes("?") ? "&" : "?";

  return `${baseUrl}${separator}path=${storyPath}`;
};

export const buildCommentBody = (
  baseUrl: string,
  targets: StoryTarget[]
): string => {
  const lines = [COMMENT_MARKER, "🚀✨ Your Storybook preview is ready!", ""];

  const linkable = targets.filter((target) => target.docsId ?? target.storyId);

  if (linkable.length > 0) {
    lines.push("Jump straight to what this pull request touches:", "");
    for (const target of linkable.slice(0, MAX_LINKS)) {
      lines.push(`- 🔗 [${target.title}](${previewUrl(baseUrl, target)})`);
    }
    if (linkable.length > MAX_LINKS) {
      lines.push(`- …and ${linkable.length - MAX_LINKS} more`);
    }
    lines.push("");
  }

  lines.push(`🔗 [View Storybook](${baseUrl}) — full preview`, "");
  lines.push("Happy reviewing! 🎉");

  return `${lines.join("\n")}\n`;
};

const readChangedFiles = (filePath: string | undefined): string[] => {
  const raw = filePath
    ? fs.readFileSync(filePath, "utf8")
    : fs.readFileSync(0, "utf8");

  return raw
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
};

const readIndex = (indexPath: string): StorybookIndex | null => {
  if (!fs.existsSync(indexPath)) {
    console.error(
      `\x1b[33m Storybook index not found at ${indexPath}, linking the preview root only \x1b[0m`
    );
    return null;
  }

  return JSON.parse(fs.readFileSync(indexPath, "utf8")) as StorybookIndex;
};

const main = (): void => {
  const baseUrl = process.env.STORYBOOK_URL;
  if (!baseUrl) {
    console.error("\x1b[33m STORYBOOK_URL is required \x1b[0m");
    process.exit(1);
    return;
  }

  const index = readIndex(process.env.STORYBOOK_INDEX ?? DEFAULT_INDEX_PATH);
  const targets = index
    ? resolveStoryTargets(readChangedFiles(process.argv[2]), index)
    : [];

  process.stdout.write(buildCommentBody(baseUrl, targets));
};

if (require.main === module) {
  main();
}
