import fs from "fs";
import path from "path";
import { compareStrings } from "./compareStrings";
import { listDirs, toPosix } from "./fileSystem";
import { normalize } from "./naming";
import type { SharedEntry } from "./SourceMap.types";

/**
 * Mirrors the component name generated by SVGR for Nimbus icon asset names.
 *
 * `arrow-left.svg` -> `ArrowLeft`
 * `user-circle.svg` -> `UserCircle`
 * `Infinite.svg` -> `Infinite`
 */
function iconComponentName(filename: string): string {
  const basename = path.basename(filename, path.extname(filename));

  return basename
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
}

/**
 * Exposes concrete icon exports in the source map so consumers do not need
 * to inspect every asset just to verify that an icon exists.
 */
function collectIconExports(assetsDir: string): string[] {
  if (!fs.existsSync(assetsDir)) {
    return [];
  }

  return fs
    .readdirSync(assetsDir, {
      withFileTypes: true,
    })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".svg"))
    .map((entry) => `${iconComponentName(entry.name)}Icon`)
    .sort(compareStrings);
}

/**
 * Resolves a component's matching style directory when one exists.
 */
export function resolveStylePath(
  cwd: string,
  stylesRoot: string | undefined,
  group: string,
  componentName: string
): string | undefined {
  if (!stylesRoot) {
    return undefined;
  }

  const groupDir = path.join(cwd, stylesRoot, group);

  if (!fs.existsSync(groupDir)) {
    return undefined;
  }

  const normalizedName = normalize(componentName);

  const matches = listDirs(groupDir).filter(
    (directory) => normalize(directory) === normalizedName
  );

  if (matches.length > 1) {
    throw new Error(
      `Ambiguous style directory for ${componentName} in ${groupDir}: ${matches.join(
        ", "
      )}`
    );
  }

  if (!matches.length) {
    return undefined;
  }

  return toPosix(path.relative(cwd, path.join(groupDir, matches[0])));
}

/**
 * Adds generated metadata to shared entries when an asset directory is
 * explicitly configured by the repository wrapper.
 */
export function enrichSharedEntries(
  sharedEntries: Record<string, SharedEntry>,
  cwd: string
): Record<string, SharedEntry> {
  const shared = Object.fromEntries(
    Object.entries(sharedEntries).map(([key, value]) => [key, { ...value }])
  );

  for (const [key, entry] of Object.entries(shared)) {
    if (!entry.assets) {
      continue;
    }

    const absoluteAssetsPath = path.resolve(cwd, entry.assets);

    if (!fs.existsSync(absoluteAssetsPath)) {
      delete shared[key].assets;
      delete shared[key].available;
      continue;
    }

    shared[key] = {
      ...entry,

      available: collectIconExports(absoluteAssetsPath),
    };
  }

  return shared;
}
