name: cleanup-storybook-preview

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write

jobs:
  cleanup-s3-preview:
    runs-on: ubuntu-latest

    steps:
      - name: 🔐 Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com 

      - name: Delete Storybook preview from S3
        run: |
          BUCKET_NAME=ns-ec-dms-bs3-nimbus-preview
          PR_ID=${{ github.event.pull_request.number }}
          PREVIEW_PATH="components/pull/$PR_ID"

          echo "Deleting S3 folder: s3://$BUCKET_NAME/$PREVIEW_PATH"
          aws s3 rm "s3://$BUCKET_NAME/$PREVIEW_PATH" --recursive
