name: "create-tag"

on: workflow_dispatch

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Generate tag release
        uses: StephaneBour/actions-calver@v1.5
        id: calver
        with:
          date_format: "%Y.%m.%d"
          release: ${{ github.ref == 'refs/heads/master' }}
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.calver.outputs.release }}
