name: "create-github-tag"

on: workflow_dispatch

jobs:
  create-github-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Generate tag release
        uses: StephaneBour/actions-calver@v1.5
        id: calver
        with:
          date_format: "%Y.%m.%d"
          release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.calver.outputs.release }}

  trigger-action-create-github-release:
    needs: [create-github-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger github action create github release
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/tiendanube/nimbus-design-system/actions/workflows/58856078/dispatches' \
          --header 'Authorization: token ${{ secrets.PAT_CHANGE_BRANCH_PROTECTION_RULES_FROM_JUNIOR_CONQUISTA }}' \
          --data '{"ref":"master"}'
