name: "Generate documentation"

on:
  push:
    branches:
      - ECNIM-707
      - "!dependabot/**/**"
    paths-ignore:
      - "**/package.json"
      - ".yarn/versions/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Read Node version
      #   id: node_version
      #   run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: subdir/package-lock.json
          # run: yarn

      - name: Cache NPM dependencies # (2)
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      # - uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

  generate-documents:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache NPM dependencies # (2)
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Generate documents
        run: yarn build:docs

      - name: Commit documents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: updated documentation for components and subcomponents"
