name: "publish-storybook"

on:
  push:
    branches:
      - master

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node-deps
        with:
          cache-mode: yarn-cache

      - name: Run build tokens
        run: npm run build:tokens

      - name: Restore built icons
        id: icons-cache
        uses: actions/cache@v4
        with:
          path: packages/icons/dist
          key: >-
            ${{ runner.os }}-icons-${{
              hashFiles(
                'packages/icons/src/**',
                'packages/icons/package.json',
                'packages/icons/svgo.config.js',
                'packages/icons/tsconfig.json',
                'packages/icons/webpack.config.ts',
                'packages/core/webpack/src/**',
                'yarn.lock'
              )
            }}

      - name: Run build icons
        if: steps.icons-cache.outputs.cache-hit != 'true'
        run: yarn build:icons

      - name: build storybook
        run: yarn build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: .build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".build-storybook"
