name: "publish-nimbus-helper"

on: workflow_dispatch

jobs:
  publish-nimbus-helper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node-deps

      - name: Install global package @vscode/vsce
        run: npm install -g @vscode/vsce

      - name: Bump version package
        run: yarn bump:stable

      - name: Publish extension in the marketplace
        working-directory: ./packages/helper
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
