name: "publish-storybook"

on:
  push:
    branches:
      - master

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node-deps

      - name: Run build tokens
        run: npm run build:tokens

      - name: Run build icons
        run: yarn build:icons

      - name: build storybook
        run: yarn build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: .build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".build-storybook"
