name: "publish-nimbus-helper"

on: workflow_dispatch

jobs:
  publish-nimbus-helper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Cache Yarn global cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules folders
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn

      - name: Install gobal package @vscode/vsce
        run: npm install -g @vscode/vsce

      - name: Bump version package
        run: yarn bump:stable

      - name: Publish extension in the marketplace
        working-directory: ./packages/helper
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
