name: "publish-nimbus-helper"

on: workflow_dispatch

jobs:
  publish-nimbus-helper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Install gobal package @vscode/vsce
        run: npm install -g @vscode/vsce

      - name: Bump version package
        run: yarn bump:stable

      - name: Publish extension in the marketplace
        working-directory: ./packages/helper
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
