name: sonarcloud
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  sonarcloud:
    name: Analyze SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-deps

      - name: Run build tokens
        run: yarn build:tokens

      - name: Run build icons
        run: yarn build:icons

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
