name: "Create Release"

on:
  push:
    branches:
      - ECNIM-642

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set node version
        id: node_version
        env:
          NVMRC: ::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version:  ${NVMRC}
          registry-url: "https://registry.npmjs.org"

      - name: Generate tag release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%Y.%m.%d"
          release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.calver.outputs.release }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.calver.outputs.release }}
          release_name: ${{ steps.calver.outputs.release }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
